/**
 * generated by Xtext 2.10.0
 */
package org.tetrabox.minijava.xtext.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class MiniJavaQuickfixProvider extends DefaultQuickfixProvider {
}
