/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.logo.xtext.scoping;

import fr.inria.diverse.logo.xtext.scoping.AbstractLogoScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class LogoScopeProvider extends AbstractLogoScopeProvider {
}
