/*
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.ale.repl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Visitor2replUiModule extends AbstractVisitor2replUiModule {
	
}
