/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.logo.xtext.ui;

import fr.inria.diverse.logo.xtext.ui.AbstractLogoUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LogoUiModule extends AbstractLogoUiModule {
  public LogoUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
