/**
 * generated by Xtext 2.10.0
 */
package org.tetrabox.minijava.xtext.ui.outline;

import java.util.function.Consumer;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.tetrabox.minijava.xtext.miniJava.Method;
import org.tetrabox.minijava.xtext.miniJava.Program;
import org.tetrabox.minijava.xtext.miniJava.TypeDeclaration;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class MiniJavaOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final Method m) {
    return true;
  }
  
  public void _createChildren(final DocumentRootNode outlineNode, final Program model) {
    final Consumer<TypeDeclaration> _function = (TypeDeclaration cl) -> {
      this.createNode(outlineNode, cl);
    };
    model.getClasses().forEach(_function);
  }
}
