/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.logo.xtext.validation;

import fr.inria.diverse.logo.xtext.validation.AbstractLogoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LogoValidator extends AbstractLogoValidator {
}
