/**
 * generated by Xtext 2.10.0
 */
package org.tetrabox.minijava.xtext.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.eclipse.xtext.xbase.lib.Extension;
import org.tetrabox.minijava.xtext.MiniJavaModelUtil;
import org.tetrabox.minijava.xtext.miniJava.Clazz;
import org.tetrabox.minijava.xtext.miniJava.Field;
import org.tetrabox.minijava.xtext.miniJava.Member;
import org.tetrabox.minijava.xtext.miniJava.Method;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class MiniJavaLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public MiniJavaLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  @Inject
  @Extension
  private MiniJavaModelUtil _miniJavaModelUtil;
  
  public StyledString text(final Member m) {
    String _memberAsString = this._miniJavaModelUtil.memberAsString(m);
    StyledString _styledString = new StyledString(_memberAsString);
    String _name = this._miniJavaModelUtil.getName(m.getTypeRef());
    String _plus = (" : " + _name);
    StyledString _styledString_1 = new StyledString(_plus, 
      StyledString.DECORATIONS_STYLER);
    return _styledString.append(_styledString_1);
  }
  
  public String image(final Method m) {
    return "methpub_obj.gif";
  }
  
  public String image(final Field f) {
    return "field_public_obj.gif";
  }
  
  public String image(final Clazz c) {
    return "_class_obj.gif";
  }
}
