/**
 * generated by Xtext 2.12.0
 */
package org.tetrabox.minijava.xtext.serializer;

import org.tetrabox.minijava.xtext.serializer.AbstractMiniJavaSyntacticSequencer;

@SuppressWarnings("all")
public class MiniJavaSyntacticSequencer extends AbstractMiniJavaSyntacticSequencer {
}
