/**
 * generated by Xtext 2.11.0
 */
package org.tetrabox.minijava.xtext.ide;

import org.tetrabox.minijava.xtext.ide.AbstractMiniJavaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MiniJavaIdeModule extends AbstractMiniJavaIdeModule {
}
