/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.logo.xtext;

import fr.inria.diverse.logo.xtext.LogoStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LogoStandaloneSetup extends LogoStandaloneSetupGenerated {
  public static void doSetup() {
    new LogoStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
