/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.logo.xtext;

import fr.inria.diverse.logo.xtext.AbstractLogoRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LogoRuntimeModule extends AbstractLogoRuntimeModule {
}
