/**
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.logo.xtext.ide;

import fr.inria.diverse.logo.xtext.ide.AbstractLogoIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LogoIdeModule extends AbstractLogoIdeModule {
}
