/**
 * generated by Xtext 2.10.0
 */
package org.tetrabox.minijava.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.tetrabox.minijava.xtext.ui.AbstractMiniJavaUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MiniJavaUiModule extends AbstractMiniJavaUiModule {
  public MiniJavaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
