/*
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.ale.repl.ide

/**
 * Use this class to register ide components.
 */
class Visitor2replIdeModule extends AbstractVisitor2replIdeModule {
	
}
