/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.tetrabox.minijava.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMiniJavaScopeProvider extends DelegatingScopeProvider {
}
